spring:
  application:
    name: goa-engagement
  profiles:
    # Profile ----------------------------------------
    active: dev
  # ------------------------------------------------
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson:
    default-property-inclusion: NON_NULL
  security:
    oauth2:
      jwk-uri: http://localhost:8080/api/goa-user/oauth2/jwks
      token-uri: http://localhost:8080/api/goa-user/oauth2/token
      api-client-id: api-client-id
      api-client-secret: api-client-secret

server:
  port: 8082

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    es.upm: DEBUG
    org.springframework.security: WARN

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
